
  - name: Hosts(1/1) - Configuration DNS Servers
    blockinfile: 
      path: /etc/hosts 
      state: present
      block: |
        {{ nfs_public_ip }}  nfs
        {{ master_public_ip }}  master
        {{ worker01_public_ip }}  worker01 
        {{ worker02_public_ip }}  worker02
      insertafter: EOF
      marker: "## {mark} DNS Servers"

