
#Activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN
  - name: Firewall(1/5) - Load br_netfilter Module
    modprobe:
      name: br_netfilter
      state: present

#Habilitar firewall transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN
  - name: Firewall(2/5) - Enable Firewall
    firewalld:
      masquerade: "yes"
      state: enabled
      permanent: yes
      immediate: yes

#Crear archivo k8s.conf para permitir que kubernetes maneje correctamente el tráfico con el cortafuegos
  - name: Firewall(3/5) - Touch k8s.conf
    file:
      path: /etc/sysctl.d/k8s.conf
      state: touch

#Modificar archivo k8s.conf para permitir que kubernetes maneje correctamente el tráfico con el cortafuegos
  - name: Firewall(4/5) - Write k8s.conf
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      state: present
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
      insertafter: EOF
      marker: "## {mark} net.bridge"

#Aplicar cambios en archivo k8s.conf para permitir que kubernetes maneje correctamente el tráfico con el cortafuegos
  - name: Firewall(5/5) - Reload sysctl
    shell: sysctl --system
