- name: Docker(1/3) - Add Docker Repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  #shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Docker(2/3) - Install Docker
  dnf:
    name: docker-ce
    state: latest
  #shell: dnf install docker-ce-19.03.14-3.el8 containerd.io -y  
  become: yes

- name: Docker(3/3) - Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

