- name: Touch Exports File
  file: 
    path: /etc/exports
    state: touch

- name: Write Line Exports File
  lineinfile: 
    path: /etc/exports
    line: '/srv/nfs "{{ item.line }}"(rw,sync)'      
  with_items:
    - { vm: 'master', line: '{{ master_private_ip }}'}
    - { vm: 'worker01', line: '{{ worker01_private_ip }}'}
    - { vm: 'worker02', line: '{{ worker02_private_ip }}'}

- name: Create nfs Directory
  file: 
    path: /srv/nfs
    state: directory

- name: Apply Configure Changes
  shell: exportfs -r && exportfs -s

