#Apertura de puertos firewall para la accesibilidad al servicio
- name: Firewall Configuration for NFS
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "nfs"
    - "rpc-bind"
    - "mountd"