
#Desactivar transparent masquerading para que los PODs no puedan comunicarse dentro del cluster mediante VXLAN
  - name: Firewall(1/4) - Disable br_netfilter Module
    modprobe:
      name: br_netfilter
      state: absent

#Deshabilitar firewall transparent masquerading para que los PODs no puedan comunicarse dentro del cluster mediante VXLAN
  - name: Firewall(2/4) - Disable Firewall
    firewalld:
      state: disabled

#Eliminar archivo k8s.conf
  - name: Firewall(3/4) - Remove k8s.conf
    file:
      path: /etc/sysctl.d/k8s.conf
      state: absent

#Aplicar cambios en archivo k8s.conf 
  - name: Firewall(4/4) - Reload sysctl
    shell: sysctl --system
