#Abrir puertos {"10250/tcp", "30000-32767/tcp", "8285/tcp", "8472/tcp"}
    - name: Config Kubernetes Workers (1/4) - Open Ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: public
      with_items:
        - "10250/tcp"
        - "30000-32767/tcp"
        - "8285/tcp"
        - "8472/tcp"

#Resultado de la ejecución kubadmin init
    - name: Config Kubernetes Workers (2/4) - Print kudeadm
      debug:
        msg: "{{ hostvars['master']['kudeadm_init'] }}"

#Ejecutar en los nodos el comando de kubeadm de la ejecución kubadmin init
    - name: Config Kubernetes Workers (3/4) - Execute kudeadm
      shell: "{{ hostvars['master']['kudeadm_init'] }}"
      when: hostvars['master']['kudeadm_init'] is search("kubeadm join")

#Guardar la ejecución de kudeadm_join para futuras comprobaciones
    - name: Config Kubernetes Workers (4/4) - Set kudeadm_join as fact
      set_fact: kudeadm_join=True
      
          
    