- name: Start Services (Red Hat)
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
    - "nfs-server"

- name: Start Services (Debian)
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  when: ansible_os_family == 'Debian'
  with_items:
    - "nfs-kernel-server"
 
