- name: Touch Exports File
  file: 
    path: /etc/exports
    state: touch

- name: Write Line Exports File
  lineinfile: 
    path: /etc/exports
    line: '/srv/nfs "{{ item.line }}"(rw,sync)'      
  with_items:
    - { vm: 'master', line: '10.0.2.4'}
    - { vm: 'worker01', line: '10.0.2.5'}
  # - { vm: 'worker02', line: '10.0.1.13'}

- name: Create nfs Directory
  file: 
    path: /srv/nfs
    state: directory

- name: Apply Configure Changes
  shell: exportfs -r && exportfs -s

