- name: Firewall Configuration for NFS
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
  with_items:
    - "nfs"
    - "rpc-bind"
    - "mountd"

- name: Reload Firewall
  systemd:
    name: firewalld    
    state: reloaded
  become: yes