#Eliminar usuario no administrador
  - name: User(1/3) - Remove {{ username }} User
    user:
      name: "{{ username }}"
      state: absent
      remove: yes

#Eliminar directorio usuario
  - name: User(2/3) - Create kube Directory
    file: 
      path: /home/{{ username }}/.kube
      state: absent

#Eliminar archivo usuario
  - name: User(3/3) - Remove {{ username }} file
    file:
      path: /etc/sudoers.d/{{ username }}
      state: absent

