#Instalar ingress controller:
  - name: Ingress Controller - Install IC
    shell: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml


  