- include_tasks: 04-kubernetes-master.yaml
  when: hostvars['worker']['kudeadm_join'] is not defined
- include_tasks: 05-sdn.yaml
  when: hostvars['worker']['kudeadm_join'] is not  defined
- include_tasks: 07-ingress_controller.yaml
  when: hostvars['worker']['kudeadm_join'] is defined
