
  - include_tasks: 01-config.yaml
    when: hostvars['worker01']['kudeadm_join'] is not defined
  # - include_tasks: 02-sdn.yaml
  #   when: hostvars['worker01']['kudeadm_join'] is not  defined
  - include_tasks: 02-sdn-azure.yaml
    when: hostvars['worker01']['kudeadm_join'] is not  defined
  - include_tasks: 03-ingress_controller.yaml
    when: hostvars['worker01']['kudeadm_join'] is defined
  - include_tasks: 04-user.yaml
    when: hostvars['worker01']['kudeadm_join'] is defined
