#Deshabilitar puertos firewall para no dar accesibilidad al servicio
  - name: Disable Firewall Configuration for NFS
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: disabled
      immediate: yes
    with_items:
      - "nfs"
      - "rpc-bind"
      - "mountd"

