#Cerrar puertos {"10250/tcp", "30000-32767/tcp", "8285/tcp", "8472/tcp"}
    - name: Config Kubernetes Workers (1/1) - Close Ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: disabled
        immediate: yes
        zone: public
      with_items:
        - "10250/tcp"
        - "30000-32767/tcp"
        - "8285/tcp"
        - "8472/tcp"
      
          
    