- name: Setup Kubernetes on Master
  hosts: master
  become: yes
  tasks:
  - name: Kubernetes Master (1/8) - Firewall Configuration for Kubernetes Services
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - "6443/tcp"
      - "2379-2380/tcp"
      - "10250/tcp"
      - "10251/tcp"
      - "10255/tcp"

  - name: Kubernetes Master (2/8) - kudeadm Configuration
    shell: kubeadm config images pull

  - name: Kubernetes Master (3/8) - Firewall Allow Access from Workers
    firewalld:
      rich_rule: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - "rule family=ipv4 source address=10.0.2.5/24 accept"
    #- "rule family=ipv4 source address=192.168.1.112/32 accept"

  - name: Kubernetes Master (4/8) - Firewall Allow Access to Localhost
    firewalld:
      rich_rule: "rule family=ipv4 source address=172.17.0.0/16 accept"
      zone: public
      permanent: yes
      state: enabled
      immediate: yes

  - name: Kubernetes Master (5pre/8) - Check Ports
    wait_for:
      port: "{{ item }}"
      state: started         
      delay: 0               
      timeout: 5
    ignore_errors: yes
    register: port
    with_items:
      - "6443"
      - "2379"
      #- "2380"
      - "10250"
      #- "10251"
      #- "10255"

  - name: Kubernetes Master (5pre/8) - Reset kudeadm
    shell: kubeadm reset -f
    when: port is search("started")

  - name: Kubernetes Master (5pre/8) - Restart kubelet Service
    systemd:
      name: kubelet
      state: restarted
      enabled: yes
    when: port is search("started")

  - name: Kubernetes Master (5/8) - Install CNI (Container Network Interface)
    shell: kubeadm init --pod-network-cidr 192.169.0.0/16
    #shell: kubeadm init --pod-network-cidr 192.169.0.0/16 --ignore-preflight-errors=NumCPU


  - name: Kubernetes Master (6/8) - Create kube Directory
    file: 
      path: /root/.kube
      state: directory

  - name: Kubernetes Master (7/8) - Copy admin.conf
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
  
  - name: Kubernetes Master (8/8) - Change admin.conf permission
    file:
      path: /etc/kubernetes/admin.conf
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"