---

- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: kubernetes/all, tags: all }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/workers, tags: workers }
  
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
