---

- hosts: all,!nfs
  vars_files:
    - "group_vars/kubernetes.yaml"
  gather_facts: true
  become: yes
  roles:
    - { role: fail-kubernetes/all, tags: all }

- hosts: master
  vars_files:
    - "group_vars/kubernetes.yaml"
  gather_facts: yes
  become: yes
  roles:
    - { role: fail-kubernetes/master, tags: master }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: fail-kubernetes/workers, tags: workers }
  
- hosts: master
  vars_files:
    - "group_vars/kubernetes.yaml"
  gather_facts: yes
  become: yes
  roles:
    - { role: fail-kubernetes/master, tags: master }
