- name: Firewall(1/5) - Transparent Masquerading = Load br_netfilter Module
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: Firewall(2/5) - Transparent Masquerading = Enable Firewall
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
  become: yes

- name: Firewall(3/5) - Handle Traffic = Touch k8s.conf
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
  become: yes

- name: Firewall(4/5) - Handle Traffic = Write k8s.conf
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    insertafter: EOF
    marker: ¨¨
  become: yes

- name: Firewall(5/5) - Handle Traffic = Reload sysctl
  shell: sysctl --system
  become: yes
