---

- name: Kubernetes - Add Kubernetes Repo (Touch)
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
  become: yes

- name: Kubernetes - Add Kubernetes Repo (Write)
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
    insertafter: EOF
  become: yes

- name: Kubernetes -  Install Binaries
  dnf: 
    name:
      - kubelet
      - kubeadm
      - kubectl 
    state: present
    update_cache: yes
    disable_excludes: kubernetes
  become: yes

- name: Kubernetes - Restart Kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
  become: yes

